apiVersion: v1

kind: Service
metadata:
  name: app-php-service
spec:
  type: NodePort
  selector:
    app: app-php
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30007 # port to be exposed in the node