apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-nodeport-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
  ports:
  - protocol: TCP
    port: 8080 # The port exposed by the service inside the cluster
    targetPort: 80 # The port on the Pod, that the container listens on
    nodePort: 30001 # The port exposed on the node (optional; auto-assigned if omitted)
