# Deploy the pod and service in the same yaml file

apiVersion: v1
kind: Pod

metadata:
  name: app4-php
spec:
  containers:
  - name: app4-php
    image: lucasbs1/app-php:1.0
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service

metadata:
  name: app4-php-service
spec:
  type: NodePort
  selector:
    app: app4-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005