apiVersion: v1
kind: Pod

metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:5.7
      env:
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306